# Generated by Django 3.1.3 on 2023-04-23 17:15

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sub_key', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('idCard', models.CharField(max_length=200)),
                ('issueDate', models.CharField(max_length=200)),
                ('github_profile', models.CharField(blank=True, max_length=1000)),
                ('gitlab_profile', models.CharField(blank=True, max_length=1000)),
                ('linkedin_profile', models.CharField(blank=True, max_length=1000)),
                ('image_profile', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('isFilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=1000)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=1000)),
                ('proficiency', models.CharField(blank=True, max_length=1000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationLicenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('organization', models.CharField(max_length=1000)),
                ('issue_date', models.DateField(blank=True)),
                ('expiration_date', models.DateField(blank=True)),
                ('credential_url', models.CharField(blank=True, max_length=10000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
    ]
